const enum CharactersActionTypes {
  SET_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT',
  SET_SELECTED_PAGE = 'SET_SELECTED_PAGE',
  SET_LAST_PAGE_NUMBER = 'SET_LAST_PAGE_NUMBER',
  LOAD_CHARACTERS_LIST = 'LOAD_CHARACTERS_LIST',
}
