export const enum CharactersActionTypes {
  SET_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT',
  SET_SELECTED_PAGE = 'SET_SELECTED_PAGE',
  SET_SORT_PARAMS = 'SET_SORT_PARAMS',
  SET_LOAD_LIST_PARAMS = 'SET_LOAD_LIST_PARAMS',
  LOAD_CHARACTERS_LIST = 'LOAD_CHARACTERS_LIST',
  LOAD_SPECIES_LIST = 'LOAD_SPECIES_LIST',
}
